### ISSUE TITLE
RuntimeError: Triton Error [CUDA]: device kernel image is invalid

### ISSUE THREAD

**Issue by Niko-zyf** [OpenGVLab/EfficientQAT#20]
Hi, you have done great works.
I can run the training code and save quant model, but I can't evaluate the quant model successfully. 
Traceback like this:

`100%|█████████████████████████████████████| 32/32 [00:00<00:00, 81.79it/s]
Loading pre-computed quantized weights...
Loading pre-computed quantized weights Successfully
[2024-09-11 11:16:44 root](main_block_ap.py 129): INFO memory footprint after loading quantized model: 4.05GiB
get_wikitext2
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Token indices sequence length is longer than the specified maximum sequence length for this model (299078 > 32768). Running this sequence through the model will result in indexing errors
  0%|                                                                                                                                    | 0/146 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/zhangyifan55/EfficientQAT/main_block_ap.py", line 181, in <module>
    main()
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/zhangyifan55/EfficientQAT/main_block_ap.py", line 175, in main
    evaluate(model, tokenizer, args,logger)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/zhangyifan55/EfficientQAT/main_block_ap.py", line 40, in evaluate
    eval_ppl(params, model)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/zhangyifan55/meituan-pytorch-quantization/mtpq/ppl_test.py", line 127, in eval_ppl
    outputs = model.transformer(batch) if model.__class__.__name__ == 'QWenLMHeadModel' else model.model(batch)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1101, in forward
    layer_outputs = decoder_layer(
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 816, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 696, in forward
    query_states = self.q_proj(hidden_states)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/zhangyifan55/EfficientQAT/quantize/int_linear_real.py", line 163, in forward
    weight = dequant_dim0(self.qweight, self.bits, self.maxq, self.infeatures, self.outfeatures)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/zhangyifan55/EfficientQAT/quantize/triton_utils/kernels.py", line 225, in dequant_dim0
    dequant_kernel_dim0[grid](
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/zhangyifan55/EfficientQAT/quantize/triton_utils/custom_autotune.py", line 93, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/zhangyifan55/EfficientQAT/quantize/triton_utils/custom_autotune.py", line 93, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/zhangyifan55/EfficientQAT/quantize/triton_utils/custom_autotune.py", line 74, in _bench
    return triton.testing.do_bench(kernel_call, quantiles=(0.5, 0.2, 0.8), rep=40)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/triton/testing.py", line 102, in do_bench
    fn()
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/zhangyifan55/EfficientQAT/quantize/triton_utils/custom_autotune.py", line 69, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/triton/runtime/jit.py", line 550, in run
    bin.c_wrapper(
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/triton/compiler/compiler.py", line 692, in __getattribute__
    self._init_handles()
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hdp/yaopeng10/env/anaconda3/envs/py310/lib/python3.10/site-packages/triton/compiler/compiler.py", line 683, in _init_handles
    mod, func, n_regs, n_spills = fn_load_binary(self.metadata["name"], self.asm[bin_path], self.shared, device)
RuntimeError: Triton Error [CUDA]: device kernel image is invalid`

**Comment by gdsaikrishna** [comment]
Hi @Niko-zyf , I encountered a similar issue, which was resolved for me by using Triton version 2.3.1. You can try with this version.
